# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sgn <- function(x) {
    .Call(`_rAutoARR_sgn`, x)
}

f1 <- function(x, resSq, n, rhs) {
    .Call(`_rAutoARR_f1`, x, resSq, n, rhs)
}

rootf1 <- function(resSq, n, rhs, low, up, tol = 0.001, maxIte = 500L) {
    .Call(`_rAutoARR_rootf1`, resSq, n, rhs, low, up, tol, maxIte)
}

f2 <- function(x, resSq, N, rhs) {
    .Call(`_rAutoARR_f2`, x, resSq, N, rhs)
}

rootf2 <- function(resSq, n, d, N, rhs, low, up, tol = 0.001, maxIte = 500L) {
    .Call(`_rAutoARR_rootf2`, resSq, n, d, N, rhs, low, up, tol, maxIte)
}

g1 <- function(x, resSq, n, rhs) {
    .Call(`_rAutoARR_g1`, x, resSq, n, rhs)
}

rootg1 <- function(resSq, n, rhs, low, up, tol = 0.001, maxIte = 500L) {
    .Call(`_rAutoARR_rootg1`, resSq, n, rhs, low, up, tol, maxIte)
}

huberDer <- function(res, tau, n) {
    .Call(`_rAutoARR_huberDer`, res, tau, n)
}

huberMean <- function(X, tol = 0.001, iteMax = 500L) {
    .Call(`_rAutoARR_huberMean`, X, tol, iteMax)
}

hMeanCov <- function(Z, n, d, N, rhs, epsilon = 0.0001, iteMax = 500L) {
    .Call(`_rAutoARR_hMeanCov`, Z, n, d, N, rhs, epsilon, iteMax)
}

huberCov <- function(X) {
    .Call(`_rAutoARR_huberCov`, X)
}

mad <- function(x) {
    .Call(`_rAutoARR_mad`, x)
}

standardize <- function(X, mx, sx, p) {
    .Call(`_rAutoARR_standardize`, X, mx, sx, p)
}

updateHuber <- function(Z, res, der, grad, n, tau, n1) {
    invisible(.Call(`_rAutoARR_updateHuber`, Z, res, der, grad, n, tau, n1))
}

adaHuberReg <- function(X, Y, tol = 0.0001, iteMax = 5000L) {
    .Call(`_rAutoARR_adaHuberReg`, X, Y, tol, iteMax)
}

huberReg <- function(X, Y, tol = 0.0001, constTau = 1.345, iteMax = 5000L) {
    .Call(`_rAutoARR_huberReg`, X, Y, tol, constTau, iteMax)
}

LnVal <- function(Y, mu, tau, n, z) {
    .Call(`_rAutoARR_LnVal`, Y, mu, tau, n, z)
}

gradientMuVal <- function(Y, mu, tau, n, z) {
    .Call(`_rAutoARR_gradientMuVal`, Y, mu, tau, n, z)
}

gradientTauVal <- function(Y, mu, tau, n, z) {
    .Call(`_rAutoARR_gradientTauVal`, Y, mu, tau, n, z)
}

agd <- function(Y, epsilon = 1e-5, iteMax = 5000L) {
    .Call(`_rAutoARR_agd`, Y, epsilon, iteMax)
}

agdBB <- function(Y, epsilon = 1e-5, iteMax = 5000L) {
    .Call(`_rAutoARR_agdBB`, Y, epsilon, iteMax)
}

agdBacktracking <- function(Y, s1 = 1.0, gamma1 = 0.5, beta1 = 0.8, s2 = 1.0, gamma2 = 0.5, beta2 = 0.8, epsilon = 1e-5, iteMax = 5000L) {
    .Call(`_rAutoARR_agdBacktracking`, Y, s1, gamma1, beta1, s2, gamma2, beta2, epsilon, iteMax)
}

